In [1]:
import json
import pandas as pd

In [2]:
with open('heels_mbb.json', 'r') as jsonfile:
    data = json.loads(jsonfile.read())
data = [d for d in data if ('Stats' in d) and ('career_stats' in d['Stats']) and ('gamehigh_stats' in d['Stats']) and ('current_stats' in d['Stats'])]
names = [d['Full Name'] for d in data]
len(data)

15

In [3]:
career_frames = [pd.DataFrame.from_dict(d['Stats']['career_stats']).apply(pd.to_numeric, errors='ignore') for d in data]
career_frames[0]

                 2016-17  2017-18  Total
3-Point FG             2        0      2
3-Point FGA           11        3     14
3-Point PCT         .182     .000   .143
AST                   49       16     65
AST/G                1.2      1.1    1.2
AVG                  1.5      1.2    1.4
BLK                    2        0      2
FO                     1        0      1
Free-Throws FT        25        3     28
Free-Throws FTA       41        4     45
Free-Throws PCT     .610     .750   .622
GP                    40       14     54
GS                     0        0      0
Minutes AVG          7.7      7.9    7.8
Minutes MIN          309      110    419
PF                    28       14     42
PTS                   61       17     78
Rebounds AVG         1.4      0.8    1.2
Rebounds DEF          49       11     60
Rebounds OFF           6        0      6
Rebounds TOT          55       11     66
STL                   21        6     27
Season           2016-17  2017-18  Total
T/O                   42        9     51
Totals FG             17        7     24
Totals FGA            60       23     83
Totals PCT          .283     .304   .289

In [4]:
gamehigh_frames = [pd.DataFrame.from_dict(d['Stats']['gamehigh_stats']).apply(pd.to_numeric, errors='ignore').transpose() for d in data]
gamehigh_frames[0]

,Opponent,Statistic,Value
3-Point Field Goal Attempts,vs. Miami,3-Point Field Goal Attempts,1
3-Point Field Goals Made,vs. Duke,3-Point Field Goals Made,0
Assists,vs. Michigan,Assists,4
Blocks,vs. Duke,Blocks,0
Field Goal Attempts,vs. Northern Iowa,Field Goal Attempts,6
Field Goals Made,vs. Northern Iowa,Field Goals Made,3
Free Throw Attempts,vs. Northern Iowa,Free Throw Attempts,4
Free Throws Made,vs. Northern Iowa,Free Throws Made,3
Minutes,vs. Northern Iowa,Minutes,18
Points,vs. Northern Iowa,Points,9
Rebounds,vs. Portland,Rebounds,4
Steals,vs. Northern Iowa,Steals,2

In [5]:
current_frames = [pd.DataFrame.from_dict(d['Stats']['current_stats']).apply(pd.to_numeric, errors='ignore').transpose() for d in data]
current_frames[0]

,3FG/A,3FG/A %,AST,AVG,BLK,DEF,Date,FGM/A,FGM/A %,FTM/A,FTM/A %,GS,MIN,OFF,Opponent,PF,PTS,STL,T/O,TOT
Bucknell,0-0,.000,1,5.5,0,2,11/15/17,1-2,.500,0-0,.000,,10,0,Bucknell,1,2,0,1,2
Duke,0-0,.000,0,2.1,0,0,02/08/18,0-1,.000,0-0,.000,,3,0,Duke,0,0,0,0,0
Miami,0-1,.000,0,1.3,0,0,02/27/18,0-1,.000,0-0,.000,,4,0,Miami,2,0,1,3,0
Michigan,0-0,.000,4,2.4,0,1,11/29/17,2-2,1.000,0-0,.000,,8,0,Michigan,0,4,0,1,1
Northern Iowa,0-0,.000,2,9.0,0,0,11/10/17,3-6,.500,3-4,.750,,18,0,Northern Iowa,2,9,2,1,0
Notre Dame,0-0,.000,0,1.7,0,0,02/12/18,0-0,.000,0-0,.000,,6,0,Notre Dame,3,0,0,0,0
Total,0-3,.000,16,1.2,0,11,,7-23,.304,3-4,.750,,110,0,Total,14,17,6,9,11
at Duke,0-0,.000,0,1.2,0,0,03/03/18,0-1,.000,0-0,.000,,5,0,at Duke,1,0,1,0,0
at LOUISVILLE,0-0,.000,2,1.5,0,0,02/17/18,0-0,.000,0-0,.000,,8,0,at LOUISVILLE,2,0,0,1,0
at North Carolina State,0-0,.000,1,1.9,0,0,02/10/18,0-0,.000,0-0,.000,,4,0,at North Carolina State,0,0,0,0,0
at STANFORD,0-1,.000,1,4.3,0,2,11/20/17,1-4,.250,0-0,.000,,12,0,at STANFORD,0,2,1,1,2
at Syracuse,0-0,.000,1,1.4,0,1,02/21/18,0-0,.000,0-0,.000,,4,0,at Syracuse,1,0,0,0,1
vs Arkansas,0-1,.000,1,2.6,0,1,11/24/17,0-2,.000,0-0,.000,,6,0,vs Arkansas,1,0,0,0,1
vs Michigan State,0-0,.000,1,2.2,0,0,11/26/17,0-1,.000,0-0,.000,,8,0,vs Michigan State,0,0,1,1,0
vs Portland,0-0,.000,2,3.3,0,4,11/23/17,0-3,.000,0-0,.000,,14,0,vs Portland,1,0,0,0,4

In [6]:
# Compare Stats for the current season between players
player_totals = {}
for i, player in enumerate(data):
    player_totals[player['Full Name']] = current_frames[i].loc[' Total']
player_compare = pd.DataFrame.from_dict(player_totals,orient="index")
player_compare.drop('Opponent', axis=1)

,3FG/A,3FG/A %,AST,AVG,BLK,DEF,Date,FGM/A,FGM/A %,FTM/A,FTM/A %,GS,MIN,OFF,PF,PTS,STL,T/O,TOT
Aaron Rohlman,0-0,.000,2,0.2,0,6,,2-2,1.000,0-0,.000,,26,2,1,4,0,2,8
Andrew Platek,9-24,.375,16,2.2,2,20,,25-51,.490,6-8,.750,,239,13,18,65,2,9,33
Brandon Huffman,0-0,.000,0,1.8,8,23,,17-32,.531,9-16,.563,,92,15,18,43,0,10,38
Brandon Robinson,8-19,.421,19,1.9,4,24,,19-50,.380,9-12,.750,,262,18,36,55,5,14,42
Cameron Johnson,39-110,.355,46,13.2,4,59,,92-213,.432,41-47,.872,,589,33,38,264,13,20,92
Garrison Brooks,0-0,.000,16,4.4,9,60,,57-102,.559,22-42,.524,,463,52,56,136,9,31,112
Joel Berry II,79-222,.356,96,17.8,11,92,,181-447,.405,92-105,.876,,982,17,48,533,32,55,109
Kane Ma,0-1,.000,0,0.3,0,1,,1-2,.500,0-0,.000,,9,0,0,2,0,0,1
Kenny Williams,60-147,.408,77,11.3,14,82,,128-268,.478,33-49,.673,,951,32,57,349,33,36,114
Luke Maye,44-95,.463,74,17.7,37,223,,223-436,.511,60-96,.625,,1011,91,76,550,31,56,314
Seventh Woods,0-3,.000,16,1.2,0,11,,7-23,.304,3-4,.750,,110,0,14,17,6,9,11
Shea Rush,1-3,.333,2,0.3,3,4,,2-9,.222,0-0,.000,,25,2,6,5,2,6,6
Sterling Manley,0-0,.000,11,5.6,22,70,,61-107,.570,51-75,.680,,325,46,40,173,2,31,116
Theo Pinson,10-44,.227,147,9.9,17,145,,105-221,.475,88-108,.815,,902,44,66,308,29,74,189
Walker Miller,0-0,.000,3,0.3,2,5,,2-6,.333,1-1,1.000,,25,1,3,5,0,1,6

In [7]:
# See who holds the record for each stat
gamehighs = []
for i, df in enumerate(gamehigh_frames):
    df['Player'] = names[i]
    gamehighs.append( df.apply(pd.to_numeric, errors='ignore') )
frame = pd.concat(gamehighs)
idx = frame.groupby('Statistic')['Value'].transform(max) == frame['Value']
frame = frame[idx]
frame['Player'] = frame.groupby('Statistic')['Player'].transform(lambda name: ', '.join(name))
frame[['Value', 'Player']]

,Value,Player
Assists,11,Theo Pinson
Free Throw Attempts,10,"Theo Pinson, Joel Berry II"
Free Throws Made,10,Theo Pinson
3-Point Field Goal Attempts,12,"Joel Berry II, Cameron Johnson, Kenny Williams"
Field Goal Attempts,23,"Joel Berry II, Luke Maye"
Free Throw Attempts,10,"Theo Pinson, Joel Berry II"
Minutes,41,Joel Berry II
3-Point Field Goal Attempts,12,"Joel Berry II, Cameron Johnson, Kenny Williams"
3-Point Field Goals Made,6,"Cameron Johnson, Kenny Williams"
3-Point Field Goal Attempts,12,"Joel Berry II, Cameron Johnson, Kenny Williams"
3-Point Field Goals Made,6,"Cameron Johnson, Kenny Williams"
Blocks,4,Luke Maye
Field Goal Attempts,23,"Joel Berry II, Luke Maye"
Field Goals Made,15,Luke Maye
Points,33,Luke Maye
Rebounds,18,Luke Maye
Steals,4,Luke Maye